### ISSUE TITLE
Disambiguate <emph> tags

### ISSUE THREAD

**Issue by JonathanReeve** [open-editions/corpus-joyce-ulysses-tei#1]
This is an umbrella issue to track these more specific issues: 

 - [ ] Disambiguate `<emph>` to `<foreign>` for foreign languages. (#2)
 - [x] Disambiguate `<emph>` to `<title>` for titles of works. (#3)
 - [ ] Disambiguate `<emph>` to `<said>` for direct and indirect speech and thought. 
 - [ ] Disambiguate `<emph>` to `<name>` for ships, horses, etc (#10)
